### ISSUE TITLE
SASS and/or LESS support?

### ISSUE THREAD

**Issue by jeromeds** [thoughtram/es6-babel-browserify-boilerplate#10]
Will be great if we had support for less and or sass don't you think?
I have something with `gulp-sass` and `gulp-minify-css`. 
What do you think?
I guess, after that, this will become es6-babel-sass-browserify-boilerplate :) hehe

**Comment by PascalPrecht** [comment]
Hey @jeromeds 

Thanks for your request, but I don't think we want to make this boilerplate more complex. However, feel free to fork this repo and make your own version! :)
